### ISSUE TITLE
Error: could not get the site PHP bin path

### ISSUE THREAD

**Issue by soderlind** [lucatume/local-addon-xdebug-control#1] opened 2017-09-18 13:05 UTC
My config:

![site-setup-local](https://user-images.githubusercontent.com/1649452/30543293-c9f82a1a-9c82-11e7-95c5-1c7bc076bb9a.png)

When activating xdebug, the console dumps the following:

```log
/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:325 Uncaught Error: could not get the site PHP bin path
    at Container.getSitePhpBin (/Users/per/Projects/Local-add-on/local-addon-xdebug-control/lib/System/Container.js:101:14)
    at Container.getSitePhpIniFilePath (/Users/per/Projects/Local-add-on/local-addon-xdebug-control/lib/System/Container.js:69:24)
    at Container.activateXdebug (/Users/per/Projects/Local-add-on/local-addon-xdebug-control/lib/System/Container.js:136:27)
    at XDebugControl.activateXdebug (/Users/per/Projects/Local-add-on/local-addon-xdebug-control/lib/Component/XDebugControl.js:77:20)
    at Object.invokeGuardedCallback (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/EventPluginHub.js:257:7)
    at runEventQueueInBatch (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:5)
    at handleTopLevelImpl (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
    at HTMLDocument.wrapped (/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:321:29)

```

**Comment by lucatume** [comment] 2017-09-18 13:13
Mac or Windows?

**Comment by lucatume** [comment] 2017-09-18 13:15
I can reproduce, looking into it.

**Comment by lucatume** [comment] 2017-09-18 13:31
I'm able to reproduce this only when I first created the site and not after that.
It must be an initialization issue: I will look into this.

**Comment by soderlind** [comment] 2017-09-19 12:00
You can use `wp` to find what you're looking for:

```sh
docker exec 8cc048fd7d30 wp --info --allow-root
```

will return

```sh
PHP binary:	/opt/php/7.0.3/bin/php
PHP version:	7.0.3
php.ini used:	/conf/php/7.0.3/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:	//wp-cli.yml
WP-CLI version:	1.1.0
```

**Comment by lucatume** [comment] 2017-09-19 14:08
I will look into that, thanks!

**Comment by soderlind** [comment] 2017-10-07 16:00
1.0 is working, but opening More->XDebug Control takes "a long time" (at least 5-10 sek) .. so long that I, the first time, clicked on another menu because I didn't belive it worked ..  and I believe `find / -name php | grep bin | grep /opt/php | cut -d '/' -f 4` is the reason it take so long.

**Comment by lucatume** [comment] 2017-10-07 16:24
The reason it takes so long is that each setting is read from the php configuration file when filling up the field list. The same happens when updating the settings. A good improvement would probably be not to populate that list on first render, when you first access the tab, and just read the settings after an update or a user triggered refresh. The same could apply to the xdebug status really. 
I will mull a bit over it and update the code; thanks for the feedback.

**Comment by lucatume** [comment] 2017-10-08 09:11
Closing this bug, opened an issue for the loading enhancement.

**Closed by lucatume** 2017-10-08 09:11 UTC
Labels: bug
